<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 50px;
  text-align: center;
  background-color: #474e5d;
  color: white;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}
</style>
</head>
<body>

<div class="about-section">
  <h1>Privacy Policy</h1>
  <p>Transcorp INC. Ltd., operates the https:// the schoolbus.rw  mobile application  

This is to inform you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
</p>
  <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
  <h3>Details</h3>
  <h3>Personal Data</h3>
  <p>We will request youPersonal Data means data about a living individual who can be identified from those data like:
• Email address
• First name and last name
• Phone number
• Address, district, Province,, City
We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information is related with our service

</p>

<h3>Usage Data</h3>
<p>Usage Data is data collected automatically either generated by the use of the Service or from the Service </p>
<h3>Data Controller</h3>
<p>
    Data Controller means a we control your data and make sure that they are safe.
</p>
<h3>User</h3>
<p>The User is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data</p>
<h3>Bussinesssales </h3>
<p>Transcorps INC. Ltd., in case a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide communication before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<h3>Disclosure for Law Enforcement</h3>
<p>
    Under certain circumstances, Transcorps INC Ltd., may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
</p>
<h3>Security of Data</h3>
<p>We are very conscious about yourThe security of your data , but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
<h3>Changes To This Privacy Policy</h3>
<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.

We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” .
</p>
</div>




</body>
</html>
